"""empty message

Revision ID: fa1f8d4c75a3
Revises: 0316645c491b
Create Date: 2019-02-05 02:53:01.941575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1f8d4c75a3'
down_revision = '0316645c491b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('posts', 'post_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
